
import Navigation from '@/components/ui/navigation';

const Terms = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-sm p-8 md:p-12">
          <h1 className="text-3xl font-serif font-bold text-gray-900 mb-8">Terms and Conditions</h1>
          <p className="text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">1. Service Overview</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                EchoMind ("the Platform") is an AI-powered emotional wellness service providing supportive conversations, 
                mood tracking, and personalized insights. The Platform is a technology provider, not a healthcare provider. 
                Licensed professionals, if accessible through the Platform, are independent contractors, not employees or 
                agents of the Company.
              </p>
              <p className="text-gray-700 leading-relaxed">
                By accessing or using the Platform, you agree to be bound by these Terms and Conditions ("Terms") and our 
                Privacy Policy. If you do not agree, you must not use the Platform.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">2. Emotional Advice & Medical Liability Disclaimer</h2>
              <div className="bg-red-50 border-l-4 border-red-400 p-4 mb-4">
                <p className="text-red-800 font-medium">
                  <strong>IMPORTANT DISCLAIMER:</strong> THE PLATFORM DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. 
                  Content generated by AI or third-party professionals is for general informational and supportive purposes only.
                </p>
              </div>
              <p className="text-gray-700 leading-relaxed mb-4">
                If you are experiencing a mental health crisis, suicidal thoughts, or severe emotional distress, 
                you must immediately call emergency services (e.g., 911 in the U.S.) or a crisis hotline.
              </p>
              <p className="text-gray-700 leading-relaxed">
                The Company disclaims all liability for reliance on Platform content. Users expressly acknowledge 
                that they use the Platform at their sole risk and responsibility.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">3. Data Usage and Collection</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                The Company collects and processes personal data, including but not limited to name, email, conversation data, 
                device information, usage patterns, and derived or anonymized data. Processing is based on contractual necessity, 
                legitimate interests (e.g., service improvement, analytics, fraud prevention), and user consent where legally required.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                Conversation data may be used to improve AI models but will be anonymized or aggregated before external use. 
                Derived or anonymized data shall be the exclusive property of the Company.
              </p>
              <p className="text-gray-700 leading-relaxed">
                Requests to access or delete data must be submitted in writing, accompanied by government-issued identification 
                and, where applicable, notarized verification.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">4. Subscription & Payment Terms</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                The Platform offers free access and a pay-per-session model. Paid sessions are $5.99 per session, 
                capped at eight (8) sessions per calendar month. Payments are processed immediately upon session completion.
              </p>
              <p className="text-gray-700 leading-relaxed">
                Refunds, if any, are issued solely at the Company's discretion, upon written request within twenty-four (24) 
                hours of session completion. Refunds are limited to the fees actually paid.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">5. User Conduct, License & Indemnification</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Users must not: (a) harass others; (b) distribute harmful, infringing, or illegal content; 
                (c) use the Platform for unlawful purposes.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                By submitting content or data, you grant the Company a perpetual, worldwide, royalty-free, irrevocable license 
                to use, reproduce, analyze, and create derivative works in anonymized or aggregated form.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                You agree to indemnify, defend, and hold harmless the Company, its affiliates, officers, employees, and agents 
                from any claims, damages, liabilities, or expenses (including attorney's fees) arising from your use of the Platform, 
                your content, or your breach of these Terms.
              </p>
              <p className="text-gray-700 leading-relaxed">
                The Company reserves the right to suspend or terminate accounts at any time, for any or no reason, 
                with or without notice.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">6. Governing Law, Arbitration & Waiver of Class Actions</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                These Terms shall be governed by the laws of the State of Delaware, USA, without regard to conflict of laws principles.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                All disputes, claims, or controversies shall be resolved exclusively through final and binding arbitration 
                administered by JAMS under its Comprehensive Arbitration Rules, with the seat of arbitration in Wilmington, Delaware. 
                Users waive any right to trial by jury, class action, class arbitration, or representative proceedings.
              </p>
              <p className="text-gray-700 leading-relaxed">
                Prior to commencing arbitration, the complaining party must submit a written Notice of Dispute to 
                <a href="mailto:legal@echomind.com" className="text-primary hover:underline"> legal@echomind.com</a> 
                within thirty (30) days of the event giving rise to the claim. Failure to comply constitutes a permanent waiver of the claim.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">7. Disclaimer of Warranties & Limitation of Liability</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                The Platform is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, express or implied. 
                The Company disclaims all warranties, including but not limited to merchantability, fitness for a particular purpose, 
                and non-infringement.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                To the maximum extent permitted by law, the Company's aggregate liability for any claims shall not exceed 
                the lesser of: (a) the total fees paid by you in the six (6) months prior to the claim, or (b) one hundred U.S. dollars ($100).
              </p>
              <p className="text-gray-700 leading-relaxed">
                The Company shall not be liable for any indirect, incidental, special, consequential, or punitive damages, 
                including but not limited to emotional distress, loss of data, profits, or goodwill.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">8. Entire Agreement & Modifications</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                These Terms, together with the Privacy Policy, constitute the entire agreement between you and the Company. 
                If any provision is deemed invalid, the remainder remains enforceable.
              </p>
              <p className="text-gray-700 leading-relaxed">
                The Company may update these Terms at any time. Notice of changes will be provided via email or in-app notification. 
                Continued use after updates constitutes acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">9. Contact</h2>
              <p className="text-gray-700 leading-relaxed">
                For questions about these Terms, contact:
                <br />
                <a href="mailto:ucchishths@gmail.com" className="text-primary hover:underline">
                  📧 ucchishths@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;

